### ISSUE TITLE
ImportError when running the demo. 

### ISSUE THREAD

**Issue by JirenJin** [belltailjp/selective_search_py#3]
➜  selective_search_py git:(master) ✗ ./demo_showcandidates.py ./0100.jpg  
Traceback (most recent call last):
  File "./demo_showcandidates.py", line 12, in <module>
    import selective_search
  File "/home/metadata/work/traffic_object_detection/selective_search_py/selective_search.py", line 10, in <module>
    import segment
ImportError: /home/metadata/work/traffic_object_detection/selective_search_py/segment.so: undefined symbol: _ZN5boost6python6detail11init_moduleER11PyModuleDefPFvvE

**Comment by JirenJin** [comment]
➜  selective_search_py git:(master) ✗ py.test
============================= test session starts ==============================
platform linux -- Python 3.4.3 -- py-1.4.26 -- pytest-2.6.4
collected 33 items / 1 errors 

test_color_space.py ...............
test_features.py ..................

==================================== ERRORS ====================================
__________________ ERROR collecting test_selective_search.py ___________________
test_selective_search.py:8: in <module>
    import selective_search
selective_search.py:10: in <module>
    import segment
E   ImportError: /home/metadata/work/traffic_object_detection/selective_search_py/segment.so: undefined symbol: _ZN5boost6python6detail11init_moduleER11PyModuleDefPFvvE
====================== 33 passed, 1 error in 1.15 seconds ======================
